name: citizen_app
description: Citizen public-safety app (PS 06)
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  geolocator: ^14.1.1
  video_player: ^2.14.0
  shared_preferences: ^2.5.5
  connectivity_plus: ^7.3.1
  firebase_core: ^3.0.0 # for push; optional for the demo
  firebase_messaging: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
